In [1]:
import pandas as pd

In [7]:
comments_iphone = pd.read_csv("comments_ml_iphone.csv")
comments_iphone = comments_iphone["comment"]
comments_iphone = pd.DataFrame(comments_iphone)
comments_iphone

                                               comment
0           Produto 100%, vale a pena custo beneficio.
1     Pensei que fosse maior,fiquei meio decepcionado.
2    Comprei um iphone 12 dessa loja ref store depo...
3    Produto com imei bloqueado por roubo! novament...
4    O produto veio bloqueado, pedindo senha, nao c...
..                                                 ...
300  Aparelho de telefone muito bom mas o carregado...
301  Estava com medo do que ia vim, mas veio super ...
302  Iphone novo em folha, veio com a saúde da bate...
303  Meu iphone 7 plus, veio c problema, o som do a...
304  Aparelho de pessima qualidade! possui falha ao...

[305 rows x 1 columns]

In [10]:
comments_samsung = pd.read_csv("comments_ml_samsung.csv")
comments_samsung = comments_samsung["comment"]
comments_samsung = pd.DataFrame(comments_samsung)
comments_samsung

                                                comment
0     Produto bom demais! atende super bem meu uso d...
1                                                   NaN
2     Excelente custo benefício, o desempenho é exce...
3     Gostei do aparelho tem me atendido perfeitamente.
4             O produto atendeu as minhas necessidades.
...                                                 ...
8136  Bom custo e benefício, simples mas para o que ...
8137   Bom produto de qualidade. Qualidade e preço bom.
8138  Gostei muito do aparelho o celular é muito bom...
8139  Bom produto, atende perfeitamente ao que se es...
8140  Celular maravilhoso!!!! só a bateria que dura ...

[8141 rows x 1 columns]

In [13]:
comments_xiaomi = pd.read_csv("comments_ml_xiaomi.csv")
comments_xiaomi = comments_xiaomi["comment"]
comments_xiaomi = pd.DataFrame(comments_xiaomi)
comments_xiaomi

                                                comment
0     O aparelho é muito bom! tem uma boa bateria, b...
1                     Passou-se três meses deu defeito.
2     Não está de acordo com a descrição ( na descri...
3     Ótimo pro que eu preciso. Só pra jogar que é u...
4     Não gostei muito do produto porque ele não peg...
...                                                 ...
7069           Um produto excelente, recomendo demais!.
7070        Muito bom recomendo!!muito bom recomendo!!.
7071         Excelente, como anunciado, muito obrigado.
7072         Ótimo smartphone. Gostei muito do produto.
7073                 Bom porém n veio o fone de ouvido.

[7074 rows x 1 columns]

In [22]:
comments = pd.concat([comments_xiaomi, comments_samsung, comments_iphone], axis = 0)
comments = comments.dropna()
isnull = comments.isnull()
isnull.any().any()

False

In [24]:
comments.to_csv("comments_concat.csv")